# Generated by Django 4.2 on 2025-11-13 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_employeeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="hire_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата приёма на работу"
            ),
        ),
    ]
