# Generated by Django 4.2 on 2025-11-12 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Номер стола"
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employeeprofile",
                        verbose_name="Закрепленный сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочее место",
                "verbose_name_plural": "Рабочие места",
            },
        ),
    ]
