# Generated by Django 4.2 on 2025-11-13 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplace",
            name="table_number",
            field=models.IntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Номер стола",
            ),
        ),
    ]
